"""Add imagens nas categorias

Revision ID: aa72ed09a3a7
Revises: dbf22f0ea0fb
Create Date: 2025-03-09 13:10:32.655960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa72ed09a3a7'
down_revision: Union[str, None] = 'dbf22f0ea0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('categories', 'image_url')
    # ### end Alembic commands ###
