"""Criando tabelas de categorias e posts

Revision ID: d99e778ba542
Revises: aa72ed09a3a7
Create Date: 2025-03-09 15:46:42.081498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99e778ba542'
down_revision: Union[str, None] = 'aa72ed09a3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
